### PR TITLE
[cdap-597] business logic update according https://issues.cask.co/browse/CDAP-597

### PR DESCRIPTION
**Pull request by kpovetkin**
Changes added only for business logic. Updates for tests would be added later.

### CODE REVIEW

**Comment by kpovetkin** [comment]
Unit tests updated.

**Comment by kpovetkin** [comment]
There is a problem with library implementation in a way asked in the [PR](https://issues.cask.co/browse/CDAP-597). Library becomes inconsistent with Java, Python ones. 
The difference is in error handling. Promises usage makes exception usage impossible. 
The new way for error handling is to use promise`s 'catch' method.

**Comment by kpovetkin** [comment]
Known issue:
 Browser tests work _only_ if html file is opened via browser. In this case tests errors could be seen in browser console. 

Requires time for the investigation.

**Comment by kpovetkin** [comment]
Integration tests have been updated for nodejs _only_. Integration tests for browser will updated when issue mentioned above would be resolved.

**Comment by kpovetkin** [comment]
Browser tests improved. Tests run correctly using browser or 'grunt' command.

**Comment by anwar6953** [comment]
Seems like request-node.js is still using the http-sync library?

```
alis-mbp:src alianwar$ grep -r http-sync .
./nodejs/package.json:    "http-sync": "0.0.5"
./request-node.js:        var httpSync = require('http-sync');
```

**Comment by anwar6953** [comment]
shouldn't the flags also be removed, which determined whether async or sync?
(since async: true is always set).

**Comment by anwar6953** [comment]
One thing I ran into while using this: I was unable to send an empty string.

In Streamwriter:
`if (!message) {
                throw new Error('"message" is required');
            }`
Instead, I think it should check if `message === undefined`, then throw the Error (And allow empty string).

**Comment by kpovetkin** [comment]
https://github.com/caskdata/cdap-ingest/pull/100#issuecomment-64174733

Empty message is the same as undefined message. Is there any reason to send an empty one?

**Comment by anwar6953** [comment]
I don't think the two are the same.

$ emptyString = "";
""
$ emptyString === undefined
false
$ emptyString == undefined
false

And one use case where empty strings would be sent is if a file was being read line by line, and each line was sent as a message. If there's an empty line, it shouldn't throw an error, right?

**Comment by kpovetkin** [comment]
I'm sorry I've muddled up undefined and boolean. Updated.

**Comment by anwar6953** [comment]
Also, the README is outdated.

The following is no longer correct:
`var streamWriter = streamClient.createWriter("streamName");`

The previous line and the write() calls can be expressed as follows, right?

```
streamClient.createWriter("newStreamName").then(function(writer){
    writer.write("Many messages sent to stream.");
    writer.write("Another message sent to stream.");
    writer.write("Multiple messages sent to stream.");
  })
```

**Comment by kpovetkin** [comment]
It's not outdated. You can do in this way:

var streamWriter = streamClient.createWriter("streamName");
streamWriter.then(function(writer){
    writer.write("Many messages sent to stream.");
    writer.write("Another message sent to stream.");
    writer.write("Multiple messages sent to stream.");
  })

**Comment by anwar6953** [comment]
Right, but the README is currently showing:
`var streamWriter = streamClient.createWriter("streamName");`
and below that its showing
`streamWriter.write("New log event");`
which no longer works.

**Comment by kpovetkin** [comment]
You are right. Updated.

**Comment by anwar6953** [comment]
All else looks good to me.
:+1: 

Fine to merge, unless others have comments.

**Comment by kpovetkin** [comment]
Problem with promises(did not fire handlers in node js console) is solved.

**Comment by anwar6953** [comment]
Looks good to me.

**Pull request merged**
